### ISSUE TITLE
Setup cypress.io UI integration Tests

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis-technical-validation#3]
Setup cypress.io UI Tests for CSIS

- [x] ~~[Fix Jenkins issues](https://github.com/clarity-h2020/csis/issues/8#issuecomment-575546178)~~
- [x] ~~create new GitHub Jenkins users~~
- [x] create 1st simple UI tests (Jenkins Job)

**Comment by p-a-s-c-a-l** [comment]
Another pitfall alert: `cypress.env.json` not recognized by running cypress process. Cypress has to be restarted before adding or making changes to `cypress.env.json`.

**Comment by p-a-s-c-a-l** [comment]
> + yarn run ci_cy

yarn run v1.10.1
error Command "ci_cy" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by p-a-s-c-a-l** [comment]
Pipeline post step is not trigged.

**Comment by p-a-s-c-a-l** [comment]
Beware of 'Lightweight checkout of Death' 💀 :

>  If selected, try to obtain the Pipeline script contents directly from the SCM without performing a full checkout. The advantage of this mode is its efficiency; however, you will not get any changelogs or polling based on the SCM. (If you use checkout scm during the build, this will populate the changelog and initialize polling.) Also build parameters will not be substituted into SCM configuration in this mode. Only selected SCM plugins support this mode.

**Comment by p-a-s-c-a-l** [comment]
There's some 'docker magic' going on: Although already checked out by Jenkins, inside of the container, there's still the old stuff. So we have to check out again.

**Comment by p-a-s-c-a-l** [comment]
> So we have to check out again.

This does not work. The local repo is cached somewhere and never updated.

**Comment by p-a-s-c-a-l** [comment]
Instead of the Jenkiansfile of the current branch, this Jenkinsfile is used:

```
// Example Jenkins pipeline with Cypress end-to-end tests running in parallel on 2 workers
// Pipeline syntax from https://jenkins.io/doc/book/pipeline/

// Setup:
//  before starting Jenkins, I have created several volumes to cache
//  Jenkins configuration, NPM modules and Cypress binary

// docker volume create jenkins-data
// docker volume create npm-cache
// docker volume create cypress-cache

// Start Jenkins command line by line:
//  - run as "root" user (insecure, contact your admin to configure user and groups!)
//  - run Docker in disconnected mode
//  - name running container "blue-ocean"
//  - map port 8080 with Jenkins UI
//  - map volumes for Jenkins data, NPM and Cypress caches
//  - pass Docker socket which allows Jenkins to start worker containers
//  - download and execute the latest BlueOcean Docker image

// docker run \
//   -u root \
//   -d \
//   --name blue-ocean \
//   -p 8080:8080 \
//   -v jenkins-data:/var/jenkins_home \
//   -v npm-cache:/root/.npm \
//   -v cypress-cache:/root/.cache \
//   -v /var/run/docker.sock:/var/run/docker.sock \
//   jenkinsci/blueocean:latest

// If you start for the very first time, inspect the logs from the running container
// to see Administrator password - you will need it to configure Jenkins via localhost:8080 UI
//    docker logs blue-ocean

pipeline {
  agent {
    // this image provides everything needed to run Cypress
    docker {
      image 'cypress/base:10'//cismet/cypress-base-10-with-jenkins-user:1.0'
      args '-e HOME=/var/jenkins_home/ -e CYPRESS_baseUrl="https://csis.myclimateservice.eu/" -e CYPRESS_user="demo"'
    }
  }

  stages {
    // first stage installs node dependencies and Cypress binary
    stage('build') {
      steps {
        // there a few default environment variables on Jenkins
        // on local Jenkins machine (assuming port 8080) see
        // http://localhost:8080/pipeline-syntax/globals#env
        echo "Running build ${env.BUILD_ID} on ${env.JENKINS_URL}"
        // sh 'npm ci'
        // sh 'export HOME=/var/jenkins_home/'
        sh 'cd && pwd'

        sh 'yarn install --frozen-lockfile'       
        sh 'yarn run cy:verify'
      }
    }
    stage('run Cypress tests') {
      steps {
        echo "Running build ${env.BUILD_ID}"
        sh "yarn run ci_cy"
      }
    }
  }
}
```

❓ ❓ ❓

**Comment by p-a-s-c-a-l** [comment]
Scenario Analysis App **crashes** Cypress with Chrome 80 on Windows:

> GET /apps/scenario-analysis/app/templates/indicatorCriteriaTableTemplate.html - - ms - -
GET /apps/scenario-analysis/app/templates/worldstateRankingTableTemplate.html - - ms - -
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
 {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)

Done in 406.13s.

**Comment by p-a-s-c-a-l** [comment]
With Firefox 73, [quick edit](https://github.com/clarity-h2020/docker-drupal/issues/141#issuecomment-596976142) strikes again:

> Uncaught AjaxError: 
An AJAX HTTP request terminated abnormally.
Debugging information follows.
Path: /quickedit/attachments
StatusText: error
ResponseText: 
ReadyState: 0

> This error originated from your application code, not from Cypress.

> When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

**Comment by p-a-s-c-a-l** [comment]
done

**Comment by p-a-s-c-a-l** [comment]
> GET /sites/default/files/report-images/2019-10/map-snapshot_36.png - - ms - -
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
 {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)

:hurtrealbad:

**Comment by p-a-s-c-a-l** [comment]
![grafik](https://user-images.githubusercontent.com/1788226/76770281-f4a1eb00-679d-11ea-91bf-19ba37278b4a.png)

❓ ❓ ❓

**Comment by p-a-s-c-a-l** [comment]
```yarn run v1.22.4
$ cypress open
It looks like this is your first time using Cypress: 4.2.0

  ×  Verifying Cypress can run C:\Users\pd\AppData\Local\Cypress\Cache\4.2.0\Cypress
    → Cypress Version: 4.2.0
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------



#
# Fatal error in , line 0
# Failed to deserialize the V8 snapshot blob. This can mean that the snapshot blob file is corrupted or missing.
#
#
#
#FailureMessage Object: 000000C47553ECD0

----------

Platform: win32 (10.0.18363)
Cypress Version: 4.2.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The terminal process terminated with exit code: 1
```

**Comment by p-a-s-c-a-l** [comment]
> # Failed to deserialize the V8 snapshot blob.

Solution: https://github.com/cypress-io/cypress/issues/5440#issuecomment-575222255

**Comment by p-a-s-c-a-l** [comment]
![grafik](https://user-images.githubusercontent.com/1788226/77315287-975eea00-6d07-11ea-8d3a-2b374eb26ade.png)

**Comment by p-a-s-c-a-l** [comment]
Click on Layer working locally bot not on CI: https://github.com/clarity-h2020/csis-technical-validation/issues/22#issuecomment-603041949 :hurtrealbad:

**Comment by p-a-s-c-a-l** [comment]
done
